name: Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config << END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
      - name: Cloning repository
        run: ssh prod 'cd itch.io-api && git pull https://${{ secrets.GH_AUTH }}:x-oauth-basic@github.com/euandrelucas/itch.io-api.git main --force'
      - name: Building container
        run: ssh prod 'bash -i -c "cd itch.io-api && docker build . -t adgdev/itchio-api"'
      - name: Stopping container
        run: ssh prod 'bash -i -c "docker rm --force itch.io"'
      - name: Starting container
        run: ssh prod 'bash -i -c "docker run -p 7986:7986 --hostname itchio -d --restart always --network host --cpuset-cpus=0-5 --memory="15g" --name itch.io adgdev/itchio-api"'